on:
  pull_request:
    branches:
      - main
jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_GITHUB_NPM_TOKEN: ${{ secrets.FONTAWESOME_GITHUB_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
          cache: npm
      - name: Installing dependencies
        run: npm ci
      - name: Running eslint
        run: npm run lint
