on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
          cache: yarn
      - name: Installing dependencies
        run: yarn install
        env:
          FONTAWESOME_GITHUB_NPM_TOKEN: ${{secrets.FONTAWESOME_GITHUB_NPM_TOKEN}}
      - name: Running eslint
        run: yarn lint
