name: Eslint
on:
  pull_request:
    branches:
      - main
jobs:
  build_lint_and_typecheck:
    name: Lint and check types
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_GITHUB_NPM_TOKEN: ${{ secrets.FONTAWESOME_GITHUB_NPM_TOKEN }}
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Installing dependencies
        run: npm ci
      - name: Building before running eslint and types check
        run: npm run build
      - name: Running eslint
        run: npm run lint
      - name: Running types check
        run: npm run ts:check
