on:
  pull_request:
    branches:
      - main
jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_GITHUB_NPM_TOKEN: ${{ secrets.FONTAWESOME_GITHUB_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Installing dependencies
        run: npm ci
      - name: Running typescript check
        run: npm run lint
      - name: Running eslint
        run: npm run ts:check
