name: On pull request opened

on:
  pull_request:
    branches: main
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    name: Auto assign owner
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
  build_lint_and_typecheck:
    name: Lint and check types
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_GITHUB_NPM_TOKEN: ${{ secrets.FONTAWESOME_GITHUB_NPM_TOKEN }}
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Installing dependencies
        run: npm ci
      - name: Building before running eslint and types check
        run: npm run build
      - name: Running eslint
        run: npm run lint
      - name: Running types check
        run: npm run ts:check
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_GITHUB_NPM_TOKEN: ${{ secrets.FONTAWESOME_GITHUB_NPM_TOKEN }}
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Installing dependencies
        run: npm ci
      - name: Running tests
        run: npm run test:cov
